# Generated by Django 2.0.4 on 2018-04-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='is_active',
        ),
    ]
